project_id = "xsbvfwxyxgnkfkafxtaa"

[functions.dispatch-ride]
verify_jwt = false

[functions.cleanup-signup-orphans]
verify_jwt = false

[functions.seed-test-rides]
verify_jwt = false

[functions.seed-test-passengers]
verify_jwt = false

[functions.seed-test-users]
verify_jwt = false
